Repository yalla-coop/connect5, pull requests merged in 2018-11, with the labels that each got.

#44 creating file structure
  .eslintrc.json
  __test__/express-initial.test.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/Components/App.css
  client/src/Components/App.js
  client/src/Components/Layouts/Home.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/bin/www
  server/controllers/index.js
  server/controllers/trainer.js
Labels: in-progress

#57 Css normalize
  client/src/index.css
  client/src/index.js
  client/src/normalize.css
Labels: awaiting-review

#59 Header
  client/.eslintrc.json
  client/public/index.html
  client/src/Components/CommonComponents/Header/Header.test.js
  client/src/Components/CommonComponents/Header/Logo.jpg
  client/src/Components/CommonComponents/Header/__snapshots__/Header.test.js.snap
  client/src/Components/CommonComponents/Header/index.js
Labels: awaiting-review

#60 Dummy data
  package.json
  server/database/dummy_data_build.js
  server/database/models/Answer.js
  server/database/models/Question.js
  server/database/surveyBuild.js
Labels: awaiting-review

#61 Navbar
  client/package-lock.json
  client/src/Components/App.js
  client/src/Components/CommonComponents/Navbar/Navbar.test.js
  client/src/Components/CommonComponents/Navbar/__snapshots__/Navbar.test.js.snap
  client/src/Components/CommonComponents/Navbar/index.js
  client/src/Components/Layouts/Home.js
  client/src/index.css
Labels: awaiting-review

#64 View sessions
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/Layouts/__snapshots__/surveyBuild.js
  client/src/Components/Layouts/view-sessions/__snapshots__/viewSessions.test.js.snap
  client/src/Components/Layouts/view-sessions/index.js
  client/src/Components/Layouts/view-sessions/styledComponents.js
  client/src/Components/Layouts/view-sessions/viewSessions.test.js
  client/src/Components/Layouts/viewSessions/__snapshots__/viewSessions.test.js.snap
  client/src/Components/Layouts/viewSessions/index.js
  client/src/Components/Layouts/viewSessions/styledComponents.js
  client/src/Components/Layouts/viewSessions/viewSessions.test.js
  server/controllers/index.js
  server/controllers/view-sessions.js
  server/database/db_connection.js
  server/database/queries/View-sessions.js
  server/database/queries/surveyBuild.js
Labels: done

#63 Add session
  .eslintrc.json
  .travis.yml
  __test__/add_session.js
  client/package-lock.json
  client/package.json
  client/src/Components/App.css
  client/src/Components/Layouts/CreateSession/CreateSession.test.js
  client/src/Components/Layouts/CreateSession/FormElements.js
  client/src/Components/Layouts/CreateSession/__snapshots__/CreateSession.test.js.snap
  client/src/Components/Layouts/CreateSession/index.js
  client/src/Components/Layouts/CreateSession/options.js
  package-lock.json
  package.json
  server/controllers/add_session.js
  server/controllers/index.js
  server/controllers/session.js
  server/database/db_connection.js
  server/database/dummy_data_build.js
  server/database/queries/add_session.js
Labels: done

#67 Session result overall
  .eslintrc.json
  __test__/get_question_results.js
  __test__/get_responses_number.js
  __test__/get_session_attendees.js
  __test__/get_session_question.js
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/Layouts/SessionResult/IndividualResults.js
  client/src/Components/Layouts/SessionResult/OverallResults/OverallResults.test.js
  client/src/Components/Layouts/SessionResult/OverallResults/Popup.js
  client/src/Components/Layouts/SessionResult/OverallResults/RadioResults.js
  client/src/Components/Layouts/SessionResult/OverallResults/Stars.js
  client/src/Components/Layouts/SessionResult/OverallResults/TextfieldResults.js
  client/src/Components/Layouts/SessionResult/OverallResults/__snapshots__/OverallResults.test.js.snap
  client/src/Components/Layouts/SessionResult/OverallResults/find_rate.js
  client/src/Components/Layouts/SessionResult/OverallResults/get_options.js
  client/src/Components/Layouts/SessionResult/OverallResults/index.js
  client/src/Components/Layouts/SessionResult/SessionResult.test.js
  client/src/Components/Layouts/SessionResult/StyledComponents.js
  client/src/Components/Layouts/SessionResult/__snapshots__/SessionResult.test.js.snap
  client/src/Components/Layouts/SessionResult/index.js
  package.json
  server/controllers/get_question_results.js
  server/controllers/get_question_type.js
  server/controllers/get_session_details.js
  server/controllers/index.js
  server/controllers/question.js
  server/controllers/session.js
  server/database/queries/get_question_results.js
  server/database/queries/get_session_attendees_number.js
  server/database/queries/get_session_questions.js
  server/database/queries/get_session_responses_number.js
Labels: awaiting-review

#68 Survey forms
  __test__/add_session.js
  __test__/get_session_question.js
  __test__/survey.queries.test.js
  client/package-lock.json
  client/src/Components/App.js
  client/src/Components/Layouts/Survey.js
  client/src/Components/Layouts/__snapshots__/surveyBuild.js
  client/src/Components/Questions.js
  client/src/Components/Questions.style.js
  client/src/Utils/getQuestions.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/getSurveyQs.js
  server/controllers/index.js
  server/controllers/surveyAnswers.js
  server/database/dummy_data_build.js
  server/database/models/Response.js
  server/database/queries/storeAnswers.js
  server/database/queries/storeResponse.js
  server/database/queries/surveyBuild.js
  server/database/queries/surveyQuestions.js
  server/database/surveyBuild.js
Labels: in-review

#70 Session details
  __test__/delete_session.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Components/App.js
  client/src/Components/Layouts/Session-Details/Actions.js
  client/src/Components/Layouts/Session-Details/Content.js
  client/src/Components/Layouts/Session-Details/Header.js
  client/src/Components/Layouts/Session-Details/Link.js
  client/src/Components/Layouts/Session-Details/Session.test.js
  client/src/Components/Layouts/Session-Details/__snapshots__/Session.test.js.snap
  client/src/Components/Layouts/Session-Details/index.js
  client/src/Components/Layouts/Session-Details/styledComponents.js
  client/src/Components/Layouts/view-sessions/index.js
  client/src/Components/Layouts/view-sessions/styledComponents.js
  client/src/normalize.css
  package-lock.json
  server/controllers/delete-sesstion.js
  server/controllers/index.js
  server/controllers/view-sessions.js
  server/database/db_Connection.js
  server/database/dummy_data_build.js
  server/database/queries/delete-session.js
Labels: awaiting-review

#77 Session result individuals
  __test__/get_session_answers.js
  __test__/login-trainer.test.js
  __test__/register-trainer.test.js
  __test__/survey.queries.test.js
  client/package-lock.json
  client/src/Components/Layouts/SessionResult/IndividualResults.js
  client/src/Components/Layouts/SessionResult/IndividualResults/Answer.js
  client/src/Components/Layouts/SessionResult/IndividualResults/IndividualResults.test.js
  client/src/Components/Layouts/SessionResult/IndividualResults/__snapshots__/IndividualResults.test.js.snap
  client/src/Components/Layouts/SessionResult/IndividualResults/get_responses_array.js
  client/src/Components/Layouts/SessionResult/IndividualResults/index.js
  client/src/Components/Layouts/SessionResult/IndividualResults/join_question_answer.js
  client/src/Components/Layouts/SessionResult/StyledComponents.js
  client/src/Components/Layouts/SessionResult/index.js
  client/src/Components/Questions.js
  server/controllers/get_session_responses.js
  server/controllers/session.js
  server/database/db_Connection.js
  server/database/dummy_data_build.js
  server/database/queries/get_session_answers.js
Labels: awaiting-review

#81 Fix promises in Survey build
  server/database/surveyBuild.js
Labels: awaiting-review, bug

#90 Edit session
  __test__/edit_session.js
  client/__mocks__/axios.js
  client/package-lock.json
  client/package.json
  client/src/Components/App.js
  client/src/Components/Layouts/EditSession/__snapshots__/edit_session.test.js.snap
  client/src/Components/Layouts/EditSession/edit_session.test.js
  client/src/Components/Layouts/EditSession/index.js
  client/src/Components/Layouts/EditSession/options.js
  client/src/Components/Layouts/EditSession/styledComponents.js
  client/src/Components/Layouts/Session-Details/Action.js
  client/src/Components/Layouts/Session-Details/Actions.js
  client/src/Components/Layouts/Session-Details/Content.js
  client/src/Components/Layouts/Session-Details/Link.js
  client/src/Components/Layouts/Session-Details/ResultBtn.js
  client/src/Components/Layouts/Session-Details/__snapshots__/Session.test.js.snap
  client/src/Components/Layouts/Session-Details/styledComponents.js
  client/src/Components/Layouts/view-sessions/__snapshots__/viewSessions.test.js.snap
  client/src/Components/Layouts/view-sessions/index.js
  client/src/Components/Layouts/view-sessions/styledComponents.js
  server/controllers/edit_session.js
  server/controllers/index.js
  server/database/queries/edit_session.js
Labels: in-review

#85 Sessions results API testing
  __test__/api/session.js
  server/controllers/get_session_details.js
  server/controllers/get_session_responses.js
  server/database/queries/get_session_responses_number.js
Labels: in-progress

#96 fix security alerts for vulnerable dependencies
  client/package-lock.json
  client/src/Components/Layouts/Session-Details/__snapshots__/Session.test.js.snap
  package-lock.json
Labels: awaiting-review, bug

#94 Results overview
  __test__/api/overview_results_routes.js
  __test__/check_trainer_session.js
  __test__/get_all_answers.js
  __test__/get_radiostar_questions.js
  __test__/get_trainer_attendees.js
  __test__/get_trainer_responses.js
  client/src/Components/App.js
  client/src/Components/Layouts/OverviewResults/AttendanceResults.js
  client/src/Components/Layouts/OverviewResults/Circle.js
  client/src/Components/Layouts/OverviewResults/OverviewResults.test.js
  client/src/Components/Layouts/OverviewResults/Popup.js
  client/src/Components/Layouts/OverviewResults/ResponsesResults.js
  client/src/Components/Layouts/OverviewResults/StyledComponents.js
  client/src/Components/Layouts/OverviewResults/__snapshots__/OverviewResults.test.js.snap
  client/src/Components/Layouts/OverviewResults/index.js
  client/src/Utils/get_aggregate_number.js
  client/src/Utils/get_average_number.js
  client/src/Utils/get_question_ids.js
  server/controllers/get_overview_results.js
  server/controllers/get_question_overview.js
  server/controllers/get_radiostar_questions.js
  server/controllers/index.js
  server/database/queries/check_trainer_session.js
  server/database/queries/get_all_answers.js
  server/database/queries/get_radiostar_questions.js
  server/database/queries/get_trainer_attendees.js
  server/database/queries/get_trainer_responses.js
Labels: awaiting-review
